import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import ThemeProvoder from "../context/ThemeProvoder";
import RootLaoutPage from "../UI/RootLaoutPage";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin-ext"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${roboto.className}  h-full antialiase`}>
      <ThemeProvoder>
        <RootLaoutPage>{children}</RootLaoutPage>
      </ThemeProvoder>
    </html>
  );
}
